#!/bin/sh

if [ -f .git/hooks/pre-commit ]; then
    if ! .git/hooks/pre-commit "$@"; then
        echo 'Local pre-commit hook failed, see above output'
        exit 1
    fi
fi

ggshield secret scan pre-commit "$@"
